[package]
name = "hymera-system-panel"
version = "0.1.0"
authors = ["--local <--local>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.39"
dioxus = { version = "0.6.1", features = ["fullstack", "desktop"] }
hyprland = "0.4.0-beta.1"
tokio = "1.42.0"

[features]
default = []
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
